/**
 * Italian translations for Kaguya reading lines (by sentence number 1–121).
 */
export const ITALIAN_BY_NUM = {
  1: 'Tempo fa, in un villaggio vicino alla capitale viveva un vecchio chiamato «tagliabambù» (Taketori no Okina).',
  2: 'Ogni giorno il nonno andava in montagna a tagliare il bambù e, con quello, tesseva ceste e faceva setacci vivendo di quel mestiere.',
  3: 'Un giorno, mentre provava a tagliare un bambù, alla base vide un bambù che luccicava. «Che bambù misterioso».',
  4: 'Il nonno, sorpreso, tagliò piano piano quel bambù e guardò. Ecco: dentro al bambù c’era una bambina piccola.',
  5: '«Che bambina carina.» Il nonno, pieno di gioia, sollevò la bambina tra le braccia e la portò a casa.',
  6: '«Questo non può che essere un dono degli dei.»',
  7: 'Anche la nonna si rallegrò e strinse la bambina tra le braccia. I due la trattarono come un tesoro e la educarono con grande cura.',
  8: 'Stranamente, dal giorno dopo, ogni volta che il nonno tagliava il bambù ne usciva a secchiate dell’oro.',
  9: 'In poco tempo il nonno divenne il più ricco del villaggio.',
  10: 'La bambina crebbe in fretta e ben presto divenne una giovane donna.',
  11: 'Splendente come se brillasse, profumata e di una bellezza tale che, per questo, fu chiamata Kaguya-hime.',
  12: 'La bellezza di Kaguya-hime si sparse fino alla capitale; uno dopo l’altro, uomini desiderosi di vederla si presentarono alla dimora del nonno.',
  13: '«Datemi Kaguya-hime per moglie, vi prego.» Gli uomini, tutti, giunsero le mani e la supplicarono.',
  14: 'Tra loro c’erano cinque uomini che, pioggia o vento, venivano alla casa del nonno dicendo che volevano assolutamente Kaguya-hime in sposa.',
  15: 'Tutti avevano un rango elevato ed erano molto ricchi.',
  16: '«Kaguya-hime è una figlia concessaci dagli dei. Non posso darla a nessuno.»',
  17: 'Per quanto il nonno rifiutasse, i cinque non si davano per vinti.',
  18: 'Il nonno, in grande imbarazzo, ne parlò con Kaguya-hime.',
  19: '«Sono tutti uomini splendidi.',
  20: 'Sposati presto e dacci pace.»',
  21: 'Allora Kaguya-hime disse:',
  22: '«In tal caso andrò in sposa a chi mi porterà una cosa straordinaria.»',
  23: 'Il nonno riferì le parole di Kaguya-hime ai cinque.',
  24: '«Principe Ishizukuri: andate in India e portate la ciotola di pietra usata dal Buddha.»',
  25: '«Principe Kuramochi: andate sul monte Hōrai e spezzate un ramo dell’albero d’oro dai frutti bianchi e portatelo.»',
  26: '«Ministro Abe: andate in Cina e portate il mantello di pelliccia del topo di fuoco.»',
  27: '«Gran consigliere Ōtomo: portate la gemma dai cinque colori che sta sul collo del drago.»',
  28: '«E consigliere Isonokami: portate il guscio che si dice nato insieme all’uovo della rondine.»',
  29: '«Sono tutti tesori che le mani degli uomini non possono ottenere.»',
  30: 'I cinque rimasero a bocca aperta e si guardarono in volto.',
  31: 'Eppure, se non riuscivano a procurarseli in qualche modo, non avrebbero potuto avere Kaguya-hime.',
  32: 'Il principe Ishizukuri mentì dicendo che andava in India e uscì dalla capitale.',
  33: 'Girò vari templi e trovò una vecchia ciotola di pietra che portò con sé.',
  34: 'La mise in un sacchetto di broccato e la portò da Kaguya-hime.',
  35: '«Finalmente ho trovato la ciotola e sono tornato dall’India.»',
  36: 'Ma Kaguya-hime guardò la ciotola sporca e disse:',
  37: '«Questa è una ciotola che avresti potuto trovare in un tempio qualsiasi, vero?',
  38: 'Se fosse davvero la ciotola del Buddha, brillerebbe di una luce molto più bella.»',
  39: 'Il principe Ishizukuri, vergognandosi, scappò di nascosto.',
  40: 'Il principe Kuramochi disse che sarebbe andato sul monte sacro e salì su una nave.',
  41: 'Ma non sapeva nemmeno dove fosse il monte sacro.',
  42: 'Allora, tornato di nascosto, radunò maestri orafi e fece fabbricare un ramo d’oro.',
  43: 'Da maestri non si poteva che aspettarsi altro.',
  44: 'Anche Kaguya-hime non riusciva a distinguerlo dal vero.',
  45: 'Mentre Kaguya-hime era perplessa, i maestri le recapitarono una lettera.',
  46: '«Pur avendo fabbricato il ramo d’oro,',
  47: 'il principe Kuramochi non ci ha pagato.',
  48: 'Vi preghiamo, principessa, di saldare voi al posto nostro.»',
  49: 'Capito subito che era un falso,',
  50: 'anche il principe Kuramochi fuggì in tutta fretta.',
  51: 'Il ministro Abe andò al porto dove attraccavano le navi dalla Cina e pagò molto denaro,',
  52: 'e si procurò il mantello di pelliccia del topo di fuoco.',
  53: 'Kaguya-hime aprì lo scrigno e vi trovò una bella pelliccia.',
  54: '«È ciò che un monaco indiano portò fino in Cina.»',
  55: 'Il ministro, soddisfatto, spiegò con orgoglio.',
  56: '«Allora mettiamola nel fuoco e vediamo.',
  57: 'Se è il mantello del topo di fuoco, non brucerà.»',
  58: 'Ma nel fuoco la pelliccia prese subito fuoco.',
  59: 'Il ministro, furibondo, disse:',
  60: '«Quel mercante mi ha osato ingannare.»',
  61: 'Il gran consigliere Ōtomo salì da solo su una nave e partì in cerca di un drago.',
  62: 'Appena fu in mare, scoppiò una terribile tempesta.',
  63: 'La nave rollava come una foglia e sembrava sul punto di affondare da un momento all’altro.',
  64: '«Perché ho cercato di catturare un drago, il re dei draghi si è adirato.»',
  65: 'Anche i marinai tremavano.',
  66: 'Il consigliere era terrorizzato.',
  67: 'Senza pensarci giunse le mani in preghiera e gridò:',
  68: '«Re dei draghi, vi prego, perdonatemi.',
  69: 'Non desidererò più la gemma del drago.»',
  70: 'Eppure per tre giorni e tre notti il mare restò in burrasca;',
  71: 'infine furono trascinati sulla spiaggia.',
  72: 'Da allora il consigliere non tornò più da Kaguya-hime.',
  73: 'Il consigliere Isonokami sorrideva tra sé.',
  74: 'I nidi di rondine si trovano ovunque.',
  75: 'Un giorno, sotto il tetto di un magazzino nel palazzo imperiale, trovò un nido di rondine.',
  76: 'Subito fece costruire un ponteggio ai servitori e calò un cesto.',
  77: 'Salito nel cesto, mise la mano nel nido e trovò il guscio.',
  78: '«L’ho trovato! Abbassate presto il cesto.»',
  79: 'Mentre i servi tiravano in fretta la corda,',
  80: 'il cesto cadde e il consigliere rovesciò sulla schiena.',
  81: 'Eppure stringeva ancora forte il guscio.',
  82: 'Ma guardandolo bene, era uno sterco di rondine.',
  83: 'Kaguya-hime, che nessuno aveva potuto sposare, divenne sempre più bella.',
  84: 'Ma giunto la primavera del quarto anno dopo,',
  85: 'Kaguya-hime, guardando la luna, piangeva sempre più spesso.',
  86: '«C’è qualcosa che ti preoccupa?»',
  87: 'Sia il nonno sia la nonna le chiesero,',
  88: 'ma lei sorrideva dolcemente e si limitava a scuotere il capo.',
  89: 'Eppure, man mano che la luna si faceva piena,',
  90: 'Kaguya-hime divenne più triste e singhiozzava.',
  91: '«Vederti così triste mi rattrista anch’io.',
  92: 'Ti prego, raccontaci il motivo.»',
  93: 'Dissero il nonno e la nonna, in lacrime.',
  94: 'Allora anche Kaguya-hime, gli occhi pieni di lacrime, disse:',
  95: '«In verità io vengo dalla capitale sulla luna.',
  96: 'Quando sarà la notte del prossimo plenilunio,',
  97: 'gli abitanti del cielo verranno a prendermi.',
  98: 'Pensare che dovrò lasciare il papà e la mamma che mi hanno voluto bene mi spezza il cuore…»',
  99: '«Non permetteremo una cosa simile», disse il nonno.',
  100: 'Il nonno chiese all’imperatore di proteggere Kaguya-hime.',
  101: 'Arrivato il giorno del plenilunio,',
  102: 'duemila attendenti dell’imperatore circondarono la casa del nonno.',
  103: 'Kaguya-hime fu messa nella stanza più interna della casa, e il nonno e la nonna la strinsero forte tra le braccia.',
  104: 'Fu sera; la luna piena cominciò a sorgere e',
  105: 'il cielo divenne chiaro come a mezzogiorno.',
  106: 'Allora una grande nube scese lentamente.',
  107: 'Sulla nube, attorno a un carro, stavano in piedi molti abitanti del cielo.',
  108: 'A tutti venne meno la forza e non riuscivano più a muovere il corpo.',
  109: 'La nube su cui erano gli abitanti del cielo',
  110: 'si fermò poco sopra il giardino, partendo dal cortile.',
  111: 'Una voce limpida risuonò ovunque.',
  112: '«Tagliabambù, siamo venuti a prendere Kaguya-hime.',
  113: 'Grazie per aver educato la principessa fino a oggi.»',
  114: 'In quell’istante, senza rumore, si aprì la porta della casa chiusa ermeticamente,',
  115: 'e Kaguya-hime si staccò dai due genitori.',
  116: 'Kaguya-hime uscì in giardino e indossò il mantello piumato delle donne del cielo.',
  117: '«Papà, mamma, è un addio. Addio.',
  118: 'Vi prego, custodite questo pensando che sono io.»',
  119: 'Kaguya-hime diede al nonno il kimono che indossava e salì sul carro.',
  120: 'Kaguya-hime, circondata dagli abitanti del cielo,',
  121: 'salì sempre più in alto nella luce splendente della luna piena.',
}
